print('farm committ successfully')
print('farm committ successfully x2')
print('коммит ради коммита')
print('чупапимуняня')
print('скоро начну норм делать')
print('очень скоро')
print('я легенда, можно умирать')
